### ISSUE TITLE
run on boot

### ISSUE THREAD

**Issue by wpa-2** [himik-genuine/raspberry_bot#1]
Works a treat and loving it, what would be the best way to get this to start on bootup ?

**Comment by himik-genuine** [comment]
There are many ways. Personally, I prefer systemd to do it for me - https://www.shellhacks.com/systemd-service-file-example/

Config may be like:
[Unit]
Description=Pibot
After=syslog.target
After=network.target

[Service]
Type=simple
User=pi
WorkingDirectory=/opt/pibot
ExecStart=/usr/bin/ruby /opt/pibot/raspberry_bot.rb
RestartSec=5
Restart=always

[Install]

**Comment by wpa-2** [comment]
```
[Unit]
Description=Pibot
After=syslog.target
After=network.target

[Service]
Type=simple
User=wpa2
WorkingDirectory=/opt/pibot
ExecStart=/usr/bin/ruby /opt/pibot/raspberry_bot.rb
RestartSec=5
Restart=always

[Install]
WantedBy=multi-user.target
```

and then I get this error 
sudo systemctl start pibot

```
Failed to start pibot.service: Unit pibot.service not found.

 ls -l /opt/pibot/
-rw-r--r-- 1 wpa2 wpa2 35149 Oct 10 18:58 LICENSE
-rw-r--r-- 1 wpa2 wpa2  1876 Oct 10 18:58 README.md
drwxr-xr-x 2 wpa2 wpa2  4096 Oct 10 18:58 app
-rw-r--r-- 1 wpa2 wpa2   271 Oct 10 19:13 bot.cfg
drwxr-xr-x 2 wpa2 wpa2  4096 Oct 10 18:58 lib
-rw-r--r-- 1 wpa2 wpa2  2037 Oct 10 18:58 raspberry_bot.rb
-rw-r--r-- 1 wpa2 wpa2    64 Oct 10 18:58 user_commands.cfg

```
I thought I would test running app outside its directory and I get this 

```
/usr/bin/ruby /opt/pibot/raspberry_bot.rb
Traceback (most recent call last):
        2: from /opt/pibot/raspberry_bot.rb:3:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ./lib/telegram_api (LoadError)


```

I know is a little out side of the app issues.

**Comment by himik-genuine** [comment]
Do you named youre config "pibot.service" and put it in the /etc/systemd/system? Do you run _sudo systemctl daemon-reload_ before trying to _systemctl start pibot_?

Error then you try running app outside its directory is... expectedly. I think i fix it later, because its sloppy, but its not the thing that bothers start app via systemd, since you have WorkingDirectory=/opt/pibot in your service file.

**Comment by wpa-2** [comment]
> Do you named youre config "pibot.service" and put it in the /etc/systemd/system? Do you run _sudo systemctl daemon-reload_ before trying to _systemctl start pibot_?
> 
> Error then you try running app outside its directory is... expectedly. I think i fix it later, because its sloppy, but its not the thing that bothers start app via systemd, since you have WorkingDirectory=/opt/pibot in your service file.

omg thank you so much, can't believe I missed that simple naming of the file. 
Thank you so much for the help, you can close/remove this now which ever suits. 

Thanks again for the great program.

**Comment by himik-genuine** [comment]
You are welcome :o)
